allowBuilds:
  '@google/genai': true
  msgpackr-extract: true
  protobufjs: true
onlyBuiltDependencies:
  - "@google/genai"
  - "@prisma/client"
  - "@prisma/engines"
  - "bcryptjs"
  - "msgpackr-extract"
  - "prisma"
  - "protobufjs"
